version: "3.9"

services:
  db:
    image: postgres
#    volumes:
#      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${BACKEND_DB_USER}
      - POSTGRES_PASSWORD=${BACKEND_DB_PASSWORD}
    ports:
      - "5432:5432"

  web:
    build:
      context: ./service
      dockerfile: Dockerfile

#    command: >
#      sh -c "python3 manage.py migrate &&
#             python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/usr/src/app/
    ports:
      - "5000:5000"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${BACKEND_DB_USER}
      - POSTGRES_PASSWORD=${BACKEND_DB_PASSWORD}

    depends_on:
      - db

#  elasticsearch:
#    image: launcher.gcr.io/google/elasticsearch2
#    ports:
#      - "9200:9200"
#      - "9300:9300"
